# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_gkecluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Networking(BaseModel):
    nodeCidr: constr(max_length=18) | None = '10.0.0.0/24'
    """
    Primary IP range for nodes.
    """
    podCidr: constr(max_length=18) | None = '10.1.0.0/16'
    """
    Secondary IP range for pods.
    """
    serviceCidr: constr(max_length=18) | None = '10.2.0.0/16'
    """
    Secondary IP range for services.
    """


class Gpu(BaseModel):
    acceleratorCount: conint(ge=1, le=16) | None = 1
    """
    Number of GPUs to attach per node.
    """
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-tesla-a100, nvidia-h100-80gb, nvidia-l4). Attached to each node along with acceleratorCount.
    """


class Zone(RootModel[constr(min_length=1, max_length=63)]):
    root: constr(min_length=1, max_length=63)


class NodePool(BaseModel):
    diskSizeGb: conint(ge=10, le=65536) | None = 100
    """
    Boot disk size in GB.
    """
    gpu: Gpu | None = None
    """
    GPU configuration. Required when role is GPU.
    """
    machineType: constr(min_length=1, max_length=63)
    """
    GCE machine type (e.g. e2-standard-4, a2-highgpu-8g, g2-standard-48).
    """
    maxNodeCount: conint(ge=0, le=1000) | None = 8
    """
    Maximum number of nodes for autoscaling.
    """
    minNodeCount: conint(ge=0, le=1000) | None = 0
    """
    Minimum number of nodes for autoscaling. Set to 1 or higher for pools that must always be available.
    """
    name: constr(min_length=1, max_length=40)
    """
    Unique name for this node pool. Used as a suffix in the GKE NodePool resource name.
    """
    nodeCount: conint(ge=0, le=1000) | None = 1
    """
    Initial number of nodes.
    """
    role: Literal['System', 'GPU']
    """
    Determines what workloads this pool runs. System pools host controllers, gateways, and infrastructure. GPU pools host inference workloads and are tainted to exclude non-GPU pods.
    """
    zones: list[Zone] | None = Field(None, max_length=8, min_length=1)
    """
    Zones to restrict this node pool to. Required for GPU pools because not all zones in a region have every GPU type. Example: ["us-central1-a", "us-central1-b"].
    """


class Spec(BaseModel):
    credentials: Credentials | None = None
    """
    GCP ProviderConfig or ClusterProviderConfig used to authenticate to the GCP API. Defaults to the ClusterProviderConfig named default.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    kubernetesVersion: constr(min_length=1, max_length=16) | None = '1.35'
    """
    GKE cluster Kubernetes version. Must be a version supported by the REGULAR release channel.
    """
    networking: Networking | None = None
    """
    VPC networking configuration. Defaults are suitable for standalone clusters. Override when VPC-peering multiple clusters to avoid CIDR collisions.
    """
    nodePools: list[NodePool] = Field(..., max_length=8, min_length=1)
    """
    Node pools for the cluster. At least one System pool is required for controllers and infrastructure workloads.
    """
    region: constr(min_length=1, max_length=32)
    """
    GCP region for the cluster (e.g. us-central1, europe-west4).
    """


class Cache(BaseModel):
    storageClassName: constr(max_length=253) | None = None
    """
    Name of the Modelplane-managed ReadWriteMany StorageClass composed on this cluster for ModelCache PVCs. ModelCache reads this to target the cache PVC.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig', 'GoogleApplicationCredentials']
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint and CA certificate. GoogleApplicationCredentials contains a GCP service account JSON key that authenticates to the cluster via GKE IAM.
    """


class Status(BaseModel):
    cache: Cache | None = None
    """
    Observed ModelCache RWX storage state.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this GKECluster.
    """


class GKECluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['GKECluster'] | None = 'GKECluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    GKEClusterSpec defines the desired state of GKECluster.
    """
    status: Status | None = None
    """
    GKEClusterStatus defines the observed state of GKECluster.
    """


class GKEClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[GKECluster]
    """
    List of gkeclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """