# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_nebiuscluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Infiniband(BaseModel):
    fabric: constr(min_length=1, max_length=63)
    """
    Identifier of the physical InfiniBand fabric to join (e.g. fabric-2). This selects existing Nebius infrastructure, not a name for a new resource: fabrics are per-region - see https://docs.nebius.com/compute/clusters/gpu#fabrics - and multi-node GPU capacity is allocated on specific fabrics, so use the fabric your capacity lives on.
    """


class Fabric(BaseModel):
    infiniband: Infiniband | None = None
    """
    InfiniBand fabric configuration. Required when type is InfiniBand.
    """
    type: Literal['None', 'InfiniBand'] | None = 'None'
    """
    Fabric technology. None uses standard VPC networking (TCP). InfiniBand places the group's nodes in a GPU cluster on a physical InfiniBand fabric for GPUDirect RDMA across nodes; only useful on InfiniBand-capable platforms (e.g. gpu-h100-sxm). When set, Modelplane composes a GPU cluster on that fabric and places the group's nodes in it.
    """


class Gpu(BaseModel):
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-h100, nvidia-l40s). Used to label GPU nodes; the actual GPU and count are determined by the platform and preset.
    """
    driversPreset: constr(min_length=1, max_length=63) | None = 'cuda13.0'
    """
    NVIDIA driver stack mk8s preinstalls on the group's nodes (e.g. cuda12.4, cuda13.0). Valid values depend on the platform and Kubernetes version, and mk8s validates them, so new presets work without a Modelplane update. Defaults to the only preset mk8s implements on the default Kubernetes version; older presets remain for older versions.
    """


class NodePool(BaseModel):
    diskSizeGb: conint(ge=10, le=65536) | None = 100
    """
    Boot disk size in GB.
    """
    fabric: Fabric | None = None
    """
    High-performance node-to-node fabric for multi-node engines, so a gang's tensor-parallel traffic isn't capped by TCP. Omit for standard VPC networking.
    """
    gpu: Gpu | None = None
    """
    GPU configuration. Required when role is GPU.
    """
    maxNodeCount: conint(ge=1, le=1000) | None = None
    """
    Maximum number of nodes for autoscaling. When set the node group autoscales between minNodeCount (or nodeCount) and this; mk8s autoscaling is server-side, no in-cluster autoscaler is installed. Omit for fixed-size groups - unlike other clouds there is no default, because mk8s node groups are either fixed size or autoscaled, never both.
    """
    minNodeCount: conint(ge=0, le=1000) | None = None
    """
    Minimum number of nodes for autoscaling. Defaults to nodeCount when maxNodeCount is set. Requires maxNodeCount.
    """
    name: constr(min_length=1, max_length=40)
    """
    Unique name for this node group. Used as a suffix in the mk8s NodeGroup resource name.
    """
    nodeCount: conint(ge=0, le=1000) | None = 1
    """
    Number of nodes. Fixed unless maxNodeCount enables autoscaling.
    """
    platform: constr(min_length=1, max_length=63)
    """
    Nebius compute platform for the group's nodes (e.g. gpu-h100-sxm, gpu-l40s-a, cpu-d3). Together with preset this replaces the instance type used by other clouds.
    """
    preset: constr(min_length=1, max_length=63)
    """
    Resource preset within the platform (e.g. 8gpu-128vcpu-1600gb, 4vcpu-16gb). Determines the GPU, vCPU, and memory shape of each node.
    """
    role: Literal['System', 'GPU']
    """
    Determines what workloads this group runs. System groups host controllers, gateways, and infrastructure. GPU groups host inference workloads and are tainted to exclude non-GPU pods.
    """


class Spec(BaseModel):
    credentials: Credentials | None = None
    """
    Nebius ProviderConfig or ClusterProviderConfig used to authenticate to the Nebius API. Defaults to the ClusterProviderConfig named default. The cluster is created in the project the referenced config sets as its projectID.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    kubernetesVersion: constr(min_length=1, max_length=16) | None = '1.34'
    """
    mk8s cluster Kubernetes version. Must be a version mk8s currently supports. Defaults to a version where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """
    nodePools: list[NodePool] = Field(..., max_length=8, min_length=1)
    """
    Node groups for the cluster. At least one System pool is required for controllers and infrastructure workloads.
    """


class Cache(BaseModel):
    storageClassName: constr(max_length=253) | None = None
    """
    Name of the Modelplane-managed ReadWriteMany StorageClass composed on this cluster for ModelCache PVCs. ModelCache reads this to target the cache PVC.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    namespace: constr(max_length=253) | None = None
    """
    Namespace of the Secret, when it isn't this NebiusCluster's namespace. Set on the credentials entry when the credential is reused from the Secret referenced by spec.credentials.
    """
    type: Literal['Kubeconfig', 'NebiusServiceAccountCredentials']
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint and CA certificate. NebiusServiceAccountCredentials contains a Nebius service account JSON key that authenticates to the cluster via Nebius IAM.
    """


class Status(BaseModel):
    cache: Cache | None = None
    """
    Observed ModelCache RWX storage state, served by the Nebius shared filesystem mounted on every node group and Nebius's csi-mounted-fs-path CSI driver.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by or passed through this cluster. Consumers use these to authenticate to the cluster. Secrets are in the same namespace as this NebiusCluster unless an entry says otherwise.
    """


class NebiusCluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['NebiusCluster'] | None = 'NebiusCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    NebiusClusterSpec defines the desired state of NebiusCluster.
    """
    status: Status | None = None
    """
    NebiusClusterStatus defines the observed state of NebiusCluster.
    """


class NebiusClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[NebiusCluster]
    """
    List of nebiusclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """