# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_inferencecluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, conint, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class Aks(BaseModel):
    credentials: Credentials | None = None
    """
    Azure ProviderConfig or ClusterProviderConfig used to authenticate to the Azure API. Defaults to the ClusterProviderConfig named default.
    """
    kubernetesVersion: str | None = '1.34'
    """
    AKS cluster Kubernetes version. Defaults to a version where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """
    location: constr(min_length=1, max_length=32)
    """
    Azure region for the cluster (e.g. westeurope, eastus2).
    """


class Eks(BaseModel):
    credentials: Credentials | None = None
    """
    AWS ProviderConfig or ClusterProviderConfig used to authenticate to the AWS API. Defaults to the ClusterProviderConfig named default.
    """
    kubernetesVersion: str | None = '1.36'
    """
    EKS cluster Kubernetes version. Defaults to a version where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """
    region: constr(min_length=1, max_length=32)
    """
    AWS region for the cluster (e.g. us-west-2).
    """


class Cache(BaseModel):
    storageClassName: constr(min_length=1, max_length=253) | None = None
    """
    Name of an existing ReadWriteMany StorageClass for ModelCache PVCs. Modelplane doesn't provision storage on an existing cluster, so the admin must create the StorageClass (it must support ReadWriteMany dynamic provisioning).
    """


class IdentitySecretRef(BaseModel):
    key: constr(min_length=1, max_length=253) | None = 'private_key'
    name: constr(min_length=1, max_length=253)
    type: (
        Literal[
            'GoogleApplicationCredentials',
            'AWSWebIdentityCredentials',
            'NebiusServiceAccountCredentials',
        ]
        | None
    ) = 'GoogleApplicationCredentials'
    """
    Cloud identity type the credential authenticates as. Must match the cloud the existing cluster runs on. Defaults to GoogleApplicationCredentials.
    """


class SecretRef(BaseModel):
    key: constr(min_length=1, max_length=253) | None = 'kubeconfig'
    name: constr(min_length=1, max_length=253)


class Existing(BaseModel):
    cache: Cache | None = None
    """
    ModelCache configuration for this cluster.
    """
    identitySecretRef: IdentitySecretRef | None = None
    """
    Optional reference to a Secret containing cloud provider credentials for IAM-based authentication. The type selects which cloud identity the ProviderConfigs authenticate as, and must match the cloud the existing cluster runs on.
    """
    secretRef: SecretRef
    """
    Reference to a Secret containing a kubeconfig for the existing cluster. The Secret must exist in the modelplane-system namespace.
    """


class Gke(BaseModel):
    credentials: Credentials | None = None
    """
    GCP ProviderConfig or ClusterProviderConfig used to authenticate to the GCP API. Defaults to the ClusterProviderConfig named default.
    """
    kubernetesVersion: str | None = '1.35'
    region: constr(min_length=1, max_length=32)


class Nebius(BaseModel):
    credentials: Credentials | None = None
    """
    Nebius ProviderConfig or ClusterProviderConfig used to authenticate to the Nebius API. Defaults to the ClusterProviderConfig named default.
    """
    kubernetesVersion: str | None = '1.34'
    """
    mk8s cluster Kubernetes version. Defaults to a version where Dynamic Resource Allocation (DRA) is generally available.
    """


class Cluster(BaseModel):
    aks: Aks | None = None
    """
    AKS cluster configuration. Required when source is AKS.
    """
    eks: Eks | None = None
    """
    EKS cluster configuration. Required when source is EKS.
    """
    existing: Existing | None = None
    """
    Bring-your-own cluster configuration. Required when source is Existing. Modelplane manages the inference stack on the cluster but does not provision the cluster itself.
    """
    gke: Gke | None = None
    """
    GKE cluster configuration. Required when source is GKE.
    """
    nebius: Nebius | None = None
    """
    Nebius mk8s cluster configuration. Required when source is Nebius; may be empty, since every field has a default. The cluster is created in the project the referenced ProviderConfig or ClusterProviderConfig sets as its projectID; Nebius projects are bound to a region, so the project also determines where the cluster runs.
    """
    source: Literal['GKE', 'EKS', 'AKS', 'Nebius', 'Existing']
    """
    Cluster provisioning method.
    """


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class CapacityBlock(BaseModel):
    capacityReservationId: constr(
        pattern=r'^cr-[0-9a-f]+$', min_length=4, max_length=64
    )
    """
    The ID of the Capacity Reservation backing the Capacity Block (e.g. cr-0123456789abcdef0). Purchasing a Capacity Block yields this ID.
    """


class Infiniband(BaseModel):
    fabric: constr(min_length=1, max_length=63)
    """
    Identifier of the physical InfiniBand fabric to join (e.g. fabric-2). This selects existing Nebius infrastructure, not a name for a new resource: fabrics are per-region - see https://docs.nebius.com/compute/clusters/gpu#fabrics - and multi-node GPU capacity is allocated on specific fabrics, so use the fabric your capacity lives on.
    """


class Fabric(BaseModel):
    infiniband: Infiniband | None = None
    """
    InfiniBand fabric configuration. Required when type is InfiniBand and the cluster source is Nebius; not used on AKS.
    """
    type: Literal['None', 'EFA', 'InfiniBand'] | None = 'None'
    """
    Fabric technology. None uses standard VPC networking (TCP). EFA attaches Elastic Fabric Adapter interfaces to each node for GPUDirect RDMA across nodes; EKS only, and only useful on EFA-capable instance types (e.g. p5en.48xlarge). When any pool sets EFA, Modelplane installs the EFA DRA driver on the cluster and the gang's pods claim EFA devices alongside their GPUs. InfiniBand places the pool's nodes on a physical InfiniBand fabric for GPUDirect RDMA across nodes; Nebius and AKS only, and only useful on InfiniBand-capable shapes (e.g. gpu-h100-sxm on Nebius, Standard_ND96isr_H100_v5 on AKS). On Nebius the pool joins the fabric named in infiniband.fabric; on AKS the pool's VM Scale Set placement group lands its nodes on one fabric, and Modelplane installs the NVIDIA network operator on the cluster.
    """


class NodePool(BaseModel):
    capacityBlock: CapacityBlock | None = None
    """
    Capacity Block reservation backing this node pool. EKS only. Large GPU instances (e.g. p5en.48xlarge) are rarely available on demand; AWS allocates them via Capacity Blocks for ML. Set this to back the pool with a Capacity Block you have purchased. The pool's zones must match the reservation's Availability Zone, and nodeCount must not exceed the reserved instance count. Omit for on-demand pools.
    """
    className: constr(min_length=1, max_length=253)
    """
    Name of the InferenceClass describing this pool's hardware.
    """
    fabric: Fabric | None = None
    """
    High-performance node-to-node fabric for multi-node engines, so a gang's tensor-parallel traffic isn't capped by TCP. Omit for standard VPC networking.
    """
    maxNodeCount: conint(ge=1) | None = None
    """
    Maximum node count for autoscaling. Omit for fixed-size pools.
    """
    minNodeCount: conint(ge=0) | None = None
    name: constr(max_length=40)
    nodeCount: conint(ge=0) | None = 1
    zones: list[str] | None = None
    """
    Zones to restrict this node pool to. Required for provisioned pools because not all zones in a region have every GPU type.
    """


class Taint(BaseModel):
    effect: Literal['NoSchedule', 'NoExecute']
    key: constr(min_length=1)
    value: str | None = None


class Spec(BaseModel):
    cluster: Cluster
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    nodePools: list[NodePool] | None = Field(None, max_length=8, min_length=1)
    """
    GPU node pools available on this cluster. Each pool references an InferenceClass that describes the hardware shape and (for provisioned clusters) how to create the pool. System pools for control-plane components are provisioned automatically.
    """
    taints: list[Taint] | None = None
    """
    Taints that repel ModelDeployments from this cluster unless they carry a matching toleration, following the Kubernetes taint model. NoSchedule keeps new replicas off the cluster while leaving existing ones in place; NoExecute additionally drains the replicas already here, which the scheduler reschedules onto other tolerated clusters (the declarative equivalent of draining a node before maintenance).
    """


class CacheModel(BaseModel):
    storageClassName: constr(max_length=253) | None = None
    """
    Effective ReadWriteMany StorageClass name for ModelCache PVCs on this cluster. ModelCache reads this to target the cache PVC.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Gateway(BaseModel):
    address: str | None = None
    """
    External IP of the inference gateway on the remote cluster. Used by ModelDeployment for unified endpoint routing.
    """


class Attributes(BaseModel):
    bool_: bool | None = Field(None, alias='bool')
    int_: int | None = Field(None, alias='int')
    string: constr(max_length=253) | None = None
    version: constr(max_length=32) | None = None


class Capacity(BaseModel):
    value: constr(max_length=32)


class Device(BaseModel):
    attributes: dict[str, Attributes] | None = Field(None, max_length=32)
    capacity: dict[str, Capacity] | None = Field(None, max_length=32)
    claim: Literal['DRA', 'Synthetic'] | None = None
    count: int | None = None
    deviceClassName: constr(max_length=253) | None = None
    driver: constr(max_length=253)
    name: constr(max_length=63)


class GpuPool(BaseModel):
    devices: list[Device] | None = Field(None, max_length=16)
    """
    Devices copied from the pool's InferenceClass. ModelDeployment.nodeSelector matches against these.
    """
    name: str
    """
    Node pool name, matching spec.nodePools[].name. Used to pin a ModelReplica to a specific pool via spec.nodePoolName.
    """
    nodes: int | None = None
    """
    Number of nodes in this pool. Derived from maxNodeCount (if autoscaling) or nodeCount.
    """


class ProviderConfigRef(BaseModel):
    name: str | None = None
    """
    Name of the ProviderConfig targeting the remote cluster. Used by ModelReplica to create resources on the cluster.
    """


class Status(BaseModel):
    cache: CacheModel | None = None
    """
    Observed ModelCache RWX storage state.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    gateway: Gateway | None = None
    gpuPools: list[GpuPool] | None = Field(None, max_length=8)
    """
    Schedulable GPU node pools on this cluster, derived from the referenced classes and the per-pool node counts. ModelDeployment scheduling matches against these.
    """
    namespace: str | None = None
    """
    Namespace where the internal XRs (cluster, backend) were created.
    """
    providerConfigRef: ProviderConfigRef | None = None


class InferenceCluster(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['InferenceCluster'] | None = 'InferenceCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Status | None = None


class InferenceClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[InferenceCluster]
    """
    List of inferenceclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """