# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_akscluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Networking(BaseModel):
    subnetCidr: constr(max_length=18) | None = '10.0.0.0/20'
    """
    CIDR of the node subnet, carved from vnetCidr.
    """
    vnetCidr: constr(max_length=18) | None = '10.0.0.0/16'
    """
    Address space for the virtual network.
    """


class Gpu(BaseModel):
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-a100, nvidia-h100). Used to label GPU nodes; the actual GPU and count are determined by the VM size.
    """


class Zone(RootModel[constr(min_length=1, max_length=8)]):
    root: constr(min_length=1, max_length=8)


class NodePool(BaseModel):
    diskSizeGb: conint(ge=10, le=65536) | None = 100
    """
    OS disk size in GB.
    """
    fabric: Literal['None', 'InfiniBand'] | None = 'None'
    """
    High-performance node-to-node fabric for multi-node engines. None uses standard VNet networking (TCP). InfiniBand relies on the pool's VM Scale Set placement group landing all nodes on one physical InfiniBand fabric. It requires the AKSInfinibandSupport feature flag on the subscription and an InfiniBand-capable VM size (e.g. Standard_ND96isr_H100_v5), and needs the NVIDIA network operator on the cluster to expose RDMA devices to pods, which Modelplane installs when any pool sets InfiniBand.
    """
    gpu: Gpu | None = None
    """
    GPU configuration. Required when role is GPU.
    """
    maxNodeCount: conint(ge=0, le=1000) | None = 8
    """
    Maximum number of nodes for autoscaling.
    """
    minNodeCount: conint(ge=0, le=1000) | None = 0
    """
    Minimum number of nodes for autoscaling. Set it to 1 or higher for GPU pools: the AKS cluster autoscaler currently cannot scale a pool whose GPUs bind through DRA up from zero nodes, so a pod scheduled to an empty pool waits forever.
    """
    name: constr(pattern=r'^[a-z][a-z0-9]{0,11}$', min_length=1, max_length=12)
    """
    Unique name for this node pool, used as the AKS agent pool name. AKS restricts Linux pool names to at most 12 lowercase alphanumeric characters starting with a letter.
    """
    nodeCount: conint(ge=0, le=1000) | None = 1
    """
    Initial number of nodes.
    """
    role: Literal['System', 'GPU']
    """
    Determines what workloads this pool runs. System pools host controllers, gateways, and infrastructure. GPU pools host inference workloads and get the NVIDIA driver installed by AKS.
    """
    vmSize: constr(min_length=1, max_length=63)
    """
    Azure VM size (e.g. Standard_D4s_v5, Standard_NC24ads_A100_v4, Standard_ND96isr_H100_v5).
    """
    zones: list[Zone] | None = Field(None, max_length=3, min_length=1)
    """
    Availability Zones to restrict this pool to (e.g. ["1"]). Optional because many GPU VM sizes are not zonal.
    """


class Spec(BaseModel):
    credentials: Credentials | None = None
    """
    Azure ProviderConfig or ClusterProviderConfig used to authenticate to the Azure API. Defaults to the ClusterProviderConfig named default.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    kubernetesVersion: constr(min_length=1, max_length=16) | None = '1.34'
    """
    AKS cluster Kubernetes version. Must be a version AKS currently supports. Defaults to a version where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """
    location: constr(min_length=1, max_length=32)
    """
    Azure region for the cluster (e.g. westeurope, eastus2).
    """
    networking: Networking | None = None
    """
    Virtual network configuration. Azure subnets span all Availability Zones in a region, so one subnet serves every node pool. Override when peering multiple clusters to avoid CIDR collisions. CIDRs must not overlap the cluster's service CIDR (10.96.0.0/16) or the overlay pod CIDR (10.244.0.0/16).
    """
    nodePools: list[NodePool] = Field(..., max_length=8, min_length=1)
    """
    Node pools for the cluster. At least one System pool is required for controllers and infrastructure workloads.
    """


class Cache(BaseModel):
    storageClassName: constr(max_length=253) | None = None
    """
    Name of the Modelplane-managed ReadWriteMany StorageClass composed on this cluster for ModelCache PVCs. ModelCache reads this to target the cache PVC.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig'] = 'Kubeconfig'
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint, CA certificate, and a client certificate for a cluster-admin local account.
    """


class Status(BaseModel):
    cache: Cache | None = None
    """
    Observed ModelCache RWX storage state.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this AKSCluster.
    """


class AKSCluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['AKSCluster'] | None = 'AKSCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    AKSClusterSpec defines the desired state of AKSCluster.
    """
    status: Status | None = None
    """
    AKSClusterStatus defines the observed state of AKSCluster.
    """


class AKSClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[AKSCluster]
    """
    List of aksclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """