# generated by datamodel-codegen:
#   filename:  workdir/gcp_m_upbound_io_v1beta1_clusterproviderconfig.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, constr

from .....k8s.apimachinery.pkg.apis.meta import v1


class Env(BaseModel):
    name: str
    """
    Name is the name of an environment variable.
    """


class Fs(BaseModel):
    path: str
    """
    Path is a filesystem path.
    """


class ImpersonateServiceAccount(BaseModel):
    name: str
    """
    GCP service account email address
    """


class SecretRef(BaseModel):
    key: str
    """
    The key to select.
    """
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Federation(BaseModel):
    providerID: constr(min_length=1)
    """
    ProviderID is the fully-qualified identifier for the identity provider on
    GCP. The format is
    `projects/<project-id>/locations/global/workloadIdentityPools/<identity-pool>/providers/<identity-provider>`.
    """
    serviceAccount: constr(min_length=1)
    """
    ServiceAccount is the email address for the attached service account.
    """


class Upbound(BaseModel):
    federation: Federation | None = None
    """
    Federation is the configuration for federated identity.
    """


class Credentials(BaseModel):
    env: Env | None = None
    """
    Env is a reference to an environment variable that contains credentials
    that must be used to connect to the provider.
    """
    fs: Fs | None = None
    """
    Fs is a reference to a filesystem location that contains credentials that
    must be used to connect to the provider.
    """
    impersonateServiceAccount: ImpersonateServiceAccount | None = None
    """
    Use GCP service account impersonation for authentication.
    """
    secretRef: SecretRef | None = None
    """
    A SecretRef is a reference to a secret key that contains the credentials
    that must be used to connect to the provider.
    """
    source: Literal[
        'None',
        'Secret',
        'AccessToken',
        'ImpersonateServiceAccount',
        'InjectedIdentity',
        'Environment',
        'Filesystem',
        'Upbound',
    ]
    """
    Source of the provider credentials.
    """
    upbound: Upbound | None = None
    """
    Upbound defines the options for authenticating using Upbound as an
    identity provider.
    """


class ExponentialFailureRateLimiter(BaseModel):
    baseDelay: str | None = None
    """
    BaseDelay is the initial delay between retries.
    """
    maxDelay: str | None = None
    """
    MaxDelay is the maximum delay between retries.
    """


class ReconciliationPolicy(BaseModel):
    exponentialFailureRateLimiter: ExponentialFailureRateLimiter | None = None
    """
    ExponentialFailureRateLimiter, when set, overrides the parameters of the
    exponential failure rate limiter used to schedule retries for the
    managed resource that this policy applies to.
    """


class Spec(BaseModel):
    credentials: Credentials
    """
    Credentials required to authenticate to this provider.
    """
    projectID: str
    """
    ProjectID is the project name (not numerical ID) of this GCP ProviderConfig.
    """
    reconciliationPolicy: ReconciliationPolicy | None = None
    """
    ReconciliationPolicy configures how a managed resource is reconciled.
    It currently allows overriding the controller's failure rate limiter
    parameters on a per-resource basis via ExponentialFailureRateLimiter.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    users: int | None = None
    """
    Users of this provider configuration.
    """


class ClusterProviderConfig(BaseModel):
    apiVersion: Literal['gcp.m.upbound.io/v1beta1'] | None = 'gcp.m.upbound.io/v1beta1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ClusterProviderConfig'] | None = 'ClusterProviderConfig'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    A ProviderConfigSpec defines the desired state of a ProviderConfig.
    """
    status: Status | None = None
    """
    A ProviderConfigStatus reflects the observed state of a ProviderConfig.
    """


class ClusterProviderConfigList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ClusterProviderConfig]
    """
    List of clusterproviderconfigs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """