# generated by datamodel-codegen:
#   filename:  workdir/gcp_upbound_io_v1beta1_providerconfigusage.yaml

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

from ....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ResourceRef(BaseModel):
    apiVersion: str
    """
    APIVersion of the referenced object.
    """
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """
    uid: str | None = None
    """
    UID of the referenced object.
    """


class ProviderConfigUsage(BaseModel):
    apiVersion: Literal['gcp.upbound.io/v1beta1'] | None = 'gcp.upbound.io/v1beta1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ProviderConfigUsage'] | None = 'ProviderConfigUsage'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    providerConfigRef: ProviderConfigRef
    """
    ProviderConfigReference to the provider config being used.
    """
    resourceRef: ResourceRef
    """
    ResourceReference to the managed resource using the provider config.
    """


class ProviderConfigUsageList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ProviderConfigUsage]
    """
    List of providerconfigusages. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """