# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_ekscluster.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class Credentials(BaseModel):
    name: constr(min_length=1, max_length=253) | None = 'default'
    type: Literal['ProviderConfig', 'ClusterProviderConfig'] | None = (
        'ClusterProviderConfig'
    )


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class SubnetCidr(RootModel[constr(max_length=18)]):
    root: constr(max_length=18)


class Networking(BaseModel):
    subnetCidrs: list[SubnetCidr] | None = Field(
        ['10.0.0.0/20', '10.0.16.0/20', '10.0.32.0/20'],
        max_length=6,
        min_length=2,
        validate_default=True,
    )
    """
    Subnet CIDRs, one per Availability Zone. EKS requires at least two subnets in different AZs. The function picks AZs by index from the region — index 0 maps to the region's first AZ alphabetically (e.g. us-west-2a), index 1 to the second, etc.
    """
    vpcCidr: constr(max_length=18) | None = '10.0.0.0/16'
    """
    Primary CIDR block for the VPC.
    """


class CapacityBlock(BaseModel):
    capacityReservationId: constr(
        pattern=r'^cr-[0-9a-f]+$', min_length=4, max_length=64
    )
    """
    The ID of the Capacity Reservation backing the Capacity Block (e.g. cr-0123456789abcdef0). Purchasing a Capacity Block yields this ID.
    """


class Gpu(BaseModel):
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-a10g, nvidia-h100, nvidia-l4). Used to label GPU nodes; the actual GPU and count are determined by the instance type.
    """


class Zone(RootModel[constr(min_length=1, max_length=63)]):
    root: constr(min_length=1, max_length=63)


class NodePool(BaseModel):
    capacityBlock: CapacityBlock | None = None
    """
    Capacity Block reservation backing this node group. Large GPU instances (e.g. p5en.48xlarge) are rarely available on demand; AWS allocates them via Capacity Blocks for ML. Set this to back the node group with a Capacity Block you have purchased. When set, Modelplane composes a launch template targeting the reservation and creates the node group with CAPACITY_BLOCK capacity type. The node group's zones must match the reservation's Availability Zone, and nodeCount must not exceed the reserved instance count. Omit for on-demand node groups.
    """
    diskSizeGb: conint(ge=10, le=65536) | None = 100
    """
    Root volume size in GB.
    """
    fabric: Literal['None', 'EFA'] | None = 'None'
    """
    High-performance node-to-node fabric for multi-node engines. None uses standard VPC networking (ENA/TCP). EFA attaches Elastic Fabric Adapter interfaces to each node via the launch template and an all-self-traffic security group, for GPUDirect RDMA across nodes. EFA is only useful on EFA-capable instance types (e.g. p5en.48xlarge) and needs the EFA DRA driver on the cluster, which Modelplane installs when any pool sets EFA.
    """
    gpu: Gpu | None = None
    """
    GPU configuration. Required when role is GPU.
    """
    instanceType: constr(min_length=1, max_length=63)
    """
    EC2 instance type (e.g. m6i.large, g6.xlarge, p4d.24xlarge).
    """
    maxNodeCount: conint(ge=0, le=1000) | None = 8
    """
    Maximum number of nodes for autoscaling.
    """
    minNodeCount: conint(ge=0, le=1000) | None = 0
    """
    Minimum number of nodes for autoscaling. Set to 1 or higher for groups that must always be available.
    """
    name: constr(min_length=1, max_length=40)
    """
    Unique name for this node group. Used as a suffix in the EKS NodeGroup resource name.
    """
    nodeCount: conint(ge=0, le=1000) | None = 1
    """
    Initial number of nodes.
    """
    role: Literal['System', 'GPU']
    """
    Determines what workloads this group runs. System groups host controllers, gateways, and infrastructure. GPU groups host inference workloads and use a GPU-enabled AMI.
    """
    zones: list[Zone] | None = Field(None, max_length=8, min_length=1)
    """
    Availability Zones to restrict this node group to. Required for GPU groups because not all AZs in a region have every instance type. Example: ["us-west-2a", "us-west-2b"].
    """


class Spec(BaseModel):
    credentials: Credentials | None = None
    """
    AWS ProviderConfig or ClusterProviderConfig used to authenticate to the AWS API. Defaults to the ClusterProviderConfig named default.
    """
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    kubernetesVersion: constr(min_length=1, max_length=16) | None = '1.36'
    """
    EKS cluster Kubernetes version. Must be a version EKS currently supports. Defaults to a version where Dynamic Resource Allocation (how GPUs bind to pods) is generally available.
    """
    networking: Networking | None = None
    """
    VPC networking configuration. Defaults give a /16 VPC carved into three /20 subnets, one per Availability Zone. Override when VPC-peering multiple clusters to avoid CIDR collisions.
    """
    nodePools: list[NodePool] = Field(..., max_length=8, min_length=1)
    """
    Node groups for the cluster. At least one System pool is required for controllers and infrastructure workloads.
    """
    region: constr(min_length=1, max_length=32)
    """
    AWS region for the cluster (e.g. us-west-2, eu-west-1).
    """


class Cache(BaseModel):
    storageClassName: constr(max_length=253) | None = None
    """
    Name of the Modelplane-managed ReadWriteMany StorageClass composed on this cluster for ModelCache PVCs. ModelCache reads this to target the cache PVC.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig'] = 'Kubeconfig'
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint, CA certificate, and a static bearer token that ClusterAuth refreshes every 10 minutes using the AWS provider's credentials.
    """


class Status(BaseModel):
    cache: Cache | None = None
    """
    Observed ModelCache RWX storage state.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    secrets: list[Secret] | None = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this EKSCluster.
    """


class EKSCluster(BaseModel):
    apiVersion: Literal['infrastructure.modelplane.ai/v1alpha1'] | None = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['EKSCluster'] | None = 'EKSCluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    EKSClusterSpec defines the desired state of EKSCluster.
    """
    status: Status | None = None
    """
    EKSClusterStatus defines the observed state of EKSCluster.
    """


class EKSClusterList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[EKSCluster]
    """
    List of eksclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """